export default [
  {
    text: 'About',
    icon: 'lightbulb',
    prefix: '/about/',
    children: ['intro', 'background', 'roadmap', 'glossary', 'community'],
  },
  {
    text: 'A.I. Inference',
    icon: 'robot',
    prefix: '/inference/',
    children: ['quick_start', 'job_schema', 'endpoints', 'writing_a_job', 'markets', 'cached_resources'],
  },
  {
    text: 'SDK',
    icon: 'code',
    prefix: '/sdk/',
    children: ['sdk_start', 'hello_world', 'tiny_llama', 'jupyter'],
  },
  {
    text: 'Inference Examples',
    icon: 'code',
    prefix: '/inference/examples/',
    collapsible: true,
    children: [
      'hello_world',
      'jupyter',
      'open_webui',
      'stable',
      'whisper',
      'ollama',
      'tinyllama',
      'multi_job',
      'vllm',
      'lmdeploy',
    ],
  },
  {
    text: 'Nodes',
    icon: 'server',
    prefix: '/nodes/',
    children: ['grid', 'grid-windows', 'grid-ubuntu', 'grid-run', 'troubleshoot'],
  },
  {
    text: 'Protocols',
    icon: 'link',
    prefix: '/protocols/',
    children: ['start', 'staking', 'rewards', 'pools', 'jobs', 'nodes', 'token'],
  },
];
