export default {
  ticker: 'NOS',
  totalSupply: 100e6,
  tokenDistribution: [
    {
      name: 'Public Sale',
      total: .03,
      lock: 0,
      vesting: 0,
      upfront: 0,
      color: '#000000',
    },
    {
      name: 'Airdrop',
      total: .05,
      lock: 0,
      vesting: 0,
      upfront: 0,
      color: '#5C2983',
    },
    {
      name: 'Liquidity',
      total: .10,
      lock: 0,
      vesting: 0,
      upfront: 0,
      color: '#F76700',
    },
    {
      name: 'Team',
      total: .20,
      lock: 0,
      vesting: 48,
      upfront: 0,
      color: '#21B372',
    },
    {
      name: 'Company',
      total: .25,
      lock: 0,
      vesting: 36,
      upfront: .10,
      color: '#FDDE02',
    },
    {
      name: 'Mining',
      total: .20,
      lock: 0,
      vesting: 24,
      upfront: 0,
      color: '#0076C5',
    },
    {
      name: 'Backers',
      total: .17,
      lock: 0,
      vesting: 9,
      upfront: .10,
      color: '#D30018',
    },
  ]
};
